---
name: 'Check for a new upstream version'
on:
  schedule:
    - cron: '59 23 * * 1'
  workflow_dispatch:

jobs:
  update-version:
    name: 'Update version'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Checkout the codebase'
        uses: 'actions/checkout@v4'

      - name: 'Update version'
        run: .github/scripts/update-version.sh windows_exporter
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
